---
deployment:
  tasks:
    - export DEPLOYPATH=/home/papebblq/research.papermensch.com/
    - /bin/mkdir -p $DEPLOYPATH/finding-aid
    - /bin/cp -f finding-aid.html $DEPLOYPATH/finding-aid/index.html
    - /bin/cp -f styles.css $DEPLOYPATH/finding-aid/
    - /bin/cp -f app.js $DEPLOYPATH/finding-aid/
    - /bin/cp -f records.json $DEPLOYPATH/finding-aid/
    - /bin/cp -f home.html $DEPLOYPATH/index.html
